---
fixtures:
  repositories:
    common: "git://github.com/simp/pupmod-simp-common"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
    iptables: "git://github.com/simp/pupmod-simp-iptables"
  symlinks:
    etcd: "#{source_dir}"
