name    'pupmod-simp-etcd'
version '0.1.0'
source 'https://github.com/simp/pupmod-simp-etcd'
author 'NickMarkowski'
license 'Apache License, Version 2.0'
summary 'A Puppet module to install and configure etcd!'
description 'A Puppet module to install and configure etcd!'
project_page 'https://github.com/simp/pupmod-simp-etcd'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
